export enum Code {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400, 
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  PAYLOAD_TOO_LARGE = 413,
  UNSUPPORTED_MEDIA_TYPE = 415,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export const CodeMessage: Record<Code, string> = {
  [Code.OK]: "request successful",
  [Code.CREATED]: "resource created successfully",
  [Code.ACCEPTED]: "request accepted for processing",
  [Code.NO_CONTENT]: "no content to return",
  [Code.BAD_REQUEST]: "bad request - invalid parameters or body",
  [Code.UNAUTHORIZED]: "unauthorized - missing or invalid authentication",
  [Code.PAYMENT_REQUIRED]: "payment required",
  [Code.FORBIDDEN]: "forbidden - you do not have permission to access this resource",
  [Code.NOT_FOUND]: "not found - the requested resource does not exist",
  [Code.METHOD_NOT_ALLOWED]: "method not allowed",
  [Code.NOT_ACCEPTABLE]: "not acceptable",
  [Code.REQUEST_TIMEOUT]: "request timeout",
  [Code.CONFLICT]: "conflict - resource already exists or conflict state",
  [Code.GONE]: "gone - resource no longer available",
  [Code.PAYLOAD_TOO_LARGE]: "payload too large",
  [Code.UNSUPPORTED_MEDIA_TYPE]: "unsupported media type",
  [Code.UNPROCESSABLE_ENTITY]: "unprocessable entity - validation failed",
  [Code.TOO_MANY_REQUESTS]: "too many requests - please try again later",
  [Code.INTERNAL_SERVER_ERROR]: "internal server error - something went wrong on our side",
  [Code.NOT_IMPLEMENTED]: "not implemented",
  [Code.BAD_GATEWAY]: "bad gateway",
  [Code.SERVICE_UNAVAILABLE]: "service unavailable",
  [Code.GATEWAY_TIMEOUT]: "gateway timeout",
};